---
apiVersion: v1
kind: Service
metadata:
  name: demo-microservice2
  labels:
    app: demo-microservice2
spec:
  type: NodePort
  selector:
    app: demo-microservice2
  ports:
  - protocol: TCP
    port: 8020
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-microservice2
spec:
  selector:
    matchLabels:
      app: demo-microservice2
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-microservice2
    spec:
      containers:
      - name: demo-microservice2
        image: mathyam/demo-microservice2:latest
        ports:
        - containerPort: 8020
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8025
          initialDelaySeconds: 30
          timeoutSeconds: 1
