---
apiVersion: v1
kind: Service
metadata:
  name: demo-microservice1
  labels:
    app: demo-microservice1
spec:
  type: NodePort
  selector:
    app: demo-microservice1
  ports:
  - protocol: TCP
    port: 8010
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-microservice1
spec:
  selector:
    matchLabels:
      app: demo-microservice1
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-microservice1
    spec:
      containers:
      - name: demo-microservice1
        image: mathyam/demo-microservice1:latest
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1
